### ISSUE TITLE
Rules tab

### ISSUE THREAD

**Issue by aliamaza** [basicDamen/chess-ai#12]
Some of the fields in the rules tab can be modified when they can be clicked. Specifically the Archers tab, the Infantry tab and the Commanding Corps section.

**Comment by basicDamen** [comment]
This can be solved by using `pointer-events: none;` in the CSS sectioning.

**Comment by basicDamen** [comment]
Solved in #16 by using the attribute `editable="false"` within the TextArea item of the Accordion.
